[package]
name = "pi_play"
version = "0.1.0"
edition = "2021"

[dependencies]
gpio = "0.4.1"
chrono = "0.4"
i2c-linux = "0.1.2"

[[bin]]
name = "pi_play"
path = "src/main.rs"

[lib]
name = "pi_play_lib"
path = "src/lib.rs"